openapi: 3.0.0
x-stoplight:
  id: fmbytjkyrgqcx
info:
  title: API Bancaria
  description: 'API para la gestión de cuentas bancarias, seguimiento de saldos y realización de transacciones.'
  version: 1.0.0
  contact:
    name: William Palacios
    email: mich.palacios.hdz@gmail.com
    url: foo.bar.com
  license:
    name: CC BY-NC 4.0
    url: 'https://fsf.org/'
tags:
  - name: Cuentas
    description: Operaciones relacionadas con la gestión de cuentas.
  - name: Transacciones
    description: Operaciones para depósitos y retiros.
paths:
  /cuentas:
    get:
      summary: Listar todas las cuentas
      tags:
        - Cuentas
      responses:
        '200':
          description: Lista de cuentas.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cuenta'
              examples:
                Example 1:
                  value:
                    - id: string
                      nombre: string
                      saldo: 0
      x-stoplight:
        id: 1bcr8eji4qqqz
      parameters:
        - schema:
            type: string
          in: header
          name: Atorization
          description: Bearer token
          required: true
        - schema:
            type: string
          in: header
          name: x-id-transaccion
          description: UUID para la traza de la operación
          required: true
        - schema:
            type: string
          in: header
          name: x-id-acceso
          description: id acceso obtenido de la API de seguridad
          required: true
      operationId: get-cuentas
      description: Servicio para la obtrención de todas las cuentas
    post:
      summary: Crear una nueva cuenta
      tags:
        - Cuentas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                saldoInicial:
                  type: number
                  format: float
              required:
                - nombre
                - saldoInicial
            examples:
              Example 1:
                value:
                  nombre: string
                  saldoInicial: -3.402823669209385e+38
      responses:
        '201':
          description: Cuenta creada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cuenta'
              examples:
                Example 1:
                  value:
                    id: string
                    nombre: string
                    saldo: 0
        '400':
          description: Solicitud inválida.
      x-stoplight:
        id: ld1o510pn9upi
      operationId: post-cuentas
      description: Servicio para la creación de cuentas
      parameters:
        - schema:
            type: string
          in: header
          name: Atorization
          description: Bearer token
          required: true
        - schema:
            type: string
          in: header
          name: x-id-transaccion
          description: UUID para la traza de la operación
          required: true
        - schema:
            type: string
          in: header
          name: x-id-acceso
          description: id acceso obtenido de la API de seguridad
          required: true
  '/cuentas/{cuentaId}':
    get:
      summary: Obtener detalles de una cuenta
      tags:
        - Cuentas
      parameters:
        - name: cuentaId
          in: path
          required: true
          schema:
            type: string
          description: id de la cuenta
        - schema:
            type: string
          in: header
          name: Atorization
          description: Bearer token
          required: true
        - schema:
            type: string
          in: header
          name: x-id-transaccion
          description: UUID para la traza de la operación
          required: true
        - schema:
            type: string
          in: header
          name: x-id-acceso
          description: id acceso obtenido de la API de seguridad
          required: true
      responses:
        '200':
          description: Detalles de la cuenta obtenidos exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cuenta'
              examples:
                Example 1:
                  value:
                    id: string
                    nombre: string
                    saldo: 0
        '404':
          description: Cuenta no encontrada.
      x-stoplight:
        id: ry9vtkq9myzkd
      operationId: get-cuenta
      description: Servicio para la obtención de una cuenta dado su ID
    patch:
      summary: Actualizar información de una cuenta
      tags:
        - Cuentas
      parameters:
        - name: cuentaId
          description: id de la cuenta
          in: path
          required: true
          schema:
            type: string
        - schema:
            type: string
          in: header
          name: Atorization
          description: Bearer token
          required: true
        - schema:
            type: string
          in: header
          name: x-id-transaccion
          description: UUID para la traza de la operación
          required: true
        - schema:
            type: string
          in: header
          name: x-id-acceso
          description: id acceso obtenido de la API de seguridad
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
            examples:
              Example 1:
                value:
                  nombre: string
      responses:
        '200':
          description: Cuenta actualizada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cuenta'
              examples:
                Example 1:
                  value:
                    id: string
                    nombre: string
                    saldo: 0
        '400':
          description: Solicitud inválida.
        '404':
          description: Cuenta no encontrada.
      x-stoplight:
        id: hzk0onyn84ss3
      operationId: update-cuenta
      description: Servicio para la actualización de la cuenta
  '/cuentas/{cuentaId}/saldo':
    get:
      summary: Obtener el saldo de una cuenta
      tags:
        - Cuentas
      parameters:
        - name: cuentaId
          description: id de la cuenta
          in: path
          required: true
          schema:
            type: string
        - schema:
            type: string
          in: header
          name: Atorization
          description: Bearer token
          required: true
        - schema:
            type: string
          in: header
          name: x-id-transaccion
          description: UUID para la traza de la operación
          required: true
        - schema:
            type: string
          in: header
          name: x-id-acceso
          description: id acceso obtenido de la API de seguridad
          required: true
      responses:
        '200':
          description: Saldo de la cuenta obtenido exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  saldo:
                    type: number
                    format: float
              examples:
                Example 1:
                  value:
                    saldo: -3.402823669209385e+38
        '404':
          description: Cuenta no encontrada.
      x-stoplight:
        id: 3cgqe2xw37oe3
      operationId: get-saldo
      description: Servicio para la consulta de saldo
  '/cuentas/{cuentaId}/transacciones':
    get:
      summary: Obtener el historial de transacciones de una cuenta
      tags:
        - Transacciones
      parameters:
        - name: cuentaId
          description: id de la cuenta
          in: path
          required: true
          schema:
            type: string
        - schema:
            type: string
          in: header
          name: Atorization
          description: Bearer token
          required: true
        - schema:
            type: string
          in: header
          name: x-id-transaccion
          description: UUID para la traza de la operación
          required: true
        - schema:
            type: string
          in: header
          name: x-id-acceso
          description: id acceso obtenido de la API de seguridad
          required: true
      responses:
        '200':
          description: Historial de transacciones obtenido exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaccion'
              examples:
                Example 1:
                  value:
                    - id: string
                      tipo: deposito
                      monto: 0
                      fecha: '2019-08-24T14:15:22Z'
        '404':
          description: Cuenta no encontrada.
      x-stoplight:
        id: wi412dswre5xp
      operationId: get-historial
      description: Servicio para la consulta del historial de saldo
    parameters:
      - schema:
          type: string
        name: cuentaId
        description: "Identificador de la cuenta"
        in: path
        required: true
    post:
      summary: Realizar un depósito o retiro
      tags:
        - Transacciones
      parameters:
        - name: cuentaId
          description: id de la cuenta
          in: path
          required: true
          schema:
            type: string
        - schema:
            type: string
          in: header
          name: Atorization
          description: Bearer token
          required: true
        - schema:
            type: string
          in: header
          name: x-id-transaccion
          description: UUID para la traza de la operación
          required: true
        - schema:
            type: string
          in: header
          name: x-id-acceso
          description: id acceso obtenido de la API de seguridad
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tipo:
                  type: string
                  enum:
                    - deposito
                    - retiro
                monto:
                  type: number
                  format: float
              required:
                - tipo
                - monto
            examples:
              Example 1:
                value:
                  tipo: deposito
                  monto: -3.402823669209385e+38
      responses:
        '200':
          description: Transacción completada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaccion'
              examples:
                Example 1:
                  value:
                    id: string
                    tipo: deposito
                    monto: 0
                    fecha: '2019-08-24T14:15:22Z'
        '400':
          description: Solicitud inválida.
        '404':
          description: Cuenta no encontrada.
      x-stoplight:
        id: t5y9tm4s35q3h
      operationId: post-transacciones
      description: Servicio para depósitos y retiros
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Cuenta:
      type: object
      properties:
        id:
          type: string
        nombre:
          type: string
        saldo:
          type: number
          format: float
      x-stoplight:
        id: qqui4u8881iib
    Transaccion:
      type: object
      properties:
        id:
          type: string
        tipo:
          type: string
          enum:
            - deposito
            - retiro
        monto:
          type: number
          format: float
        fecha:
          type: string
          format: date-time
      x-stoplight:
        id: zym97masqr5qt
security:
  - BearerAuth: []

